### ISSUE TITLE
File sorting broken on Windows

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1176]
Original issue reported here: http://dev.gbif.org/issues/browse/POR-2730

The problem occurs while trying to sort a file during the validation step (of publishing) that checks if the unique identifier is always present and unique. The problem prevents publishing from finishing. 

The problem can be triggered by an empty line at the end of the file being sorted. A known workaround, is to remove the empty line, and then re-upload and republish the resource. 

The root of the problem is that we are not respecting the rules of compareTo in our [LineComparator](https://github.com/gbif/gbif-common/blob/master/src/main/java/org/gbif/utils/text/LineComparator.java)

Please be aware this has only been observed in an IPT installed on the following environment:
* OS Version: Windows Server 2012 Datacenter Edition (64 bit)
* Java version: 1.8.0_20

Additional information:
Stacktrace:
`
Validating the core record ID http://rs.tdwg.org/dwc/terms/occurrenceID is always present and unique. Depending on the number of records, this can take a while.
Archive generation failed!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(Unknown Source)
        at java.util.TimSort.mergeAt(Unknown Source)
        at java.util.TimSort.mergeCollapse(Unknown Source)
        at java.util.TimSort.sort(Unknown Source)
        at java.util.Arrays.sort(Unknown Source)
        at java.util.Collections.sort(Unknown Source)
        at org.gbif.utils.file.FileUtils.sortAndWrite(FileUtils.java:793)
        at org.gbif.utils.file.FileUtils.sortInJava(FileUtils.java:634)
        at org.gbif.utils.file.FileUtils.sort(FileUtils.java:592)
        at org.gbif.ipt.task.GenerateDwca.sortCoreDataFile(GenerateDwca.java:358)
        at org.gbif.ipt.task.GenerateDwca.validateCoreDataFile(GenerateDwca.java:386)
        at org.gbif.ipt.task.GenerateDwca.validate(GenerateDwca.java:324)
        at org.gbif.ipt.task.GenerateDwca.call(GenerateDwca.java:544)
        at org.gbif.ipt.task.GenerateDwca.call(GenerateDwca.java:51)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
`

**Comment by kbraak** [comment]
In theory this issue has been fixed by the following commit: https://github.com/gbif/gbif-common/commit/bb7ab4930ec8e3ed8cc9b3d98c68a05af41ea501

Closing issue.
