### ISSUE TITLE
Error deleting admin account

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1203]
Affects IPT v2.3.1

To reproduce, login as one admin, and try to delete other admin account

Stacktrace copied below

---

java.lang.NullPointerException at org.gbif.ipt.service.admin.impl.UserAccountManagerImpl.delete(UserAccountManagerImpl.java:144) at org.gbif.ipt.action.admin.UserAccountsAction.delete(UserAccountsAction.java:57) at org.gbif.ipt.action.POSTAction.execute(POSTAction.java:39) at

**Comment by kbraak** [comment]
The root of this error is that one resource got into an invalid state by losing its creator. I suspect it was caused by a bad manual edit. 

Cannot reproduce, closing issue.
