### ISSUE TITLE
Source Data - Microsoft SQL Server: NULL values crash DwC-A generation

### ISSUE THREAD

**Issue by bart-v** [gbif/ipt#1212]
Whenever any of the fields fields are NULL in a resource, and a Microsoft SQL Server connection is used in the "Source Data", the generation of the DwC-A file fails:

ERROR 07-Oct-2015 10:51:34 [org.gbif.ipt.task.GenerateDwca] - Fatal DwC-A Generator Error encountered
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.google.common.base.Joiner.toString(Joiner.java:433)
        at com.google.common.base.Joiner.appendTo(Joiner.java:111)
        at com.google.common.base.Joiner.appendTo(Joiner.java:152)
        at com.google.common.base.Joiner.join(Joiner.java:193)
        at com.google.common.base.Joiner.join(Joiner.java:183)
        at com.google.common.base.Joiner.join(Joiner.java:201)
        at org.gbif.ipt.task.GenerateDwca.isEmptyLine(GenerateDwca.java:1576)
        at org.gbif.ipt.task.GenerateDwca.dumpData(GenerateDwca.java:1166)
        at org.gbif.ipt.task.GenerateDwca.addDataFile(GenerateDwca.java:206)
        at org.gbif.ipt.task.GenerateDwca.createDataFiles(GenerateDwca.java:1047)
        at org.gbif.ipt.task.GenerateDwca.call(GenerateDwca.java:943)
        at org.gbif.ipt.task.GenerateDwca.call(GenerateDwca.java:64)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

The preview on the Source Data (10 rows) still works.
The preview on the Darwin Core Mappings fails:

Mapping preview failed
Log Messages
Generating mapping preview failed: Error writing data file for mapping Darwin Core Occurrence in source ipt_test, line 1 11:04:42 AM

**Comment by kbraak** [comment]
Thanks for reporting this issue. 

It has been fixed already. Please see issue #1205. 

A new minor version 2.3.2 including this fix will be released shortly.

**Comment by kbraak** [comment]
Dear @bart-v we'd really appreciate it if you could help us validate that this issue has been fixed. 

To test, all you have to do is [download v2.3.2-SNAPSHOT.war](https://dl.dropboxusercontent.com/u/4552753/ipt-2.3.2-SNAPSHOT-r6eaa448.war), configure it in **test** mode, and publish a simple resource that uses a Microsoft SQL Server connection. Thanks a lot.

**Comment by bart-v** [comment]
Tested and confirming working now, thanks!

**Comment by kbraak** [comment]
That's wonderful news. Thank you very much for taking the time to help test and provide this feedback. Version 2.3.2 should be made available this week, pending only a bit more testing.

**Comment by peterdesmet** [comment]
Tested in `2.3.2 SNAPSHOT`: seems fixed on our side too. I can't confirm 100% as I'm using our test DB, which I only assume has NULL values like our production DB.

Thanks for the quick fix @kbraak!
