### ISSUE TITLE
NPE thrown while validating Occurrence extension

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1218]
Affects version 2.3.X

Stacktrace: 

java.lang.NullPointerException
	at org.gbif.ipt.task.GenerateDwca.validateExtensionDataFile(GenerateDwca.java:510)
	at org.gbif.ipt.task.GenerateDwca.validateExtensionDataFiles(GenerateDwca.java:435)
	at org.gbif.ipt.task.GenerateDwca.validate(GenerateDwca.java:374)
	at org.gbif.ipt.task.GenerateDwca.call(GenerateDwca.java:952)
	at org.gbif.ipt.task.GenerateDwca.call(GenerateDwca.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kbraak** [comment]
The issue appears while trying to republish a resource that hasn't been modified for a long time. 

To work around the issue, simply re-save the extension mapping, and republish again.

**Comment by meliezer** [comment]
Thank you Kyle, I had the same problem with the MoF extension, and your work-around has saved me! :)

**Comment by AaronWilton** [comment]
have also encountered this issue after an IPT software update (IPT Version 2.3.2-rea67259), and resolved in same manner.
