### ISSUE TITLE
NFS lock file prevents deletion of resource

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1311]
When the IPT data directory is on an NFS volume, an NFS lock file in the resource directory prevents the deletion of the resource. This lock file is likely the result of a file input stream or similar not being closed properly. 

Instructions on how to reproduce the issue, including screenshot of the issue and stacktrace are included below. 

**To reproduce:**
1. configure IPT instance using IPT directory on NFS
2. create a new empty resource 
3. upload a new file source, click add, then save
4. click delete button on resource overview page (produces result shown in screenshot attached)

**Screenshot:**
<img width="958" alt="screen shot 2017-01-04 at 11 57 45" src="https://cloud.githubusercontent.com/assets/5981100/21640296/29b2cf2e-d275-11e6-83dd-7699a5028682.png">

**Stacktrace:**
```
ERROR Failed to remove resource.
java.io.IOException: Unable to delete file: /var/lib/tomcat/ipt-giasip-data/resources/test1234567/sources/.nfs0000000007750a8000000004
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2381)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372)
	at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.delete(ResourceManagerImpl.java:703)
	at org.gbif.ipt.action.manage.OverviewAction.delete(OverviewAction.java:267)
```

**Comment by kbraak** [comment]
Closing additional instances in commit https://github.com/gbif/ipt/commit/fdcb647d8f28b61eaf857fdc646d1cfd5ba30902 fixed this issue, allowing the fix to be included in version 2.3.4.

A reminder https://github.com/gbif/dwca-io/issues/22 still needs fixing, at which point the IPT should upgrade to this newer version of dwca-io to ensure more CSVReader instances get closed properly.
