### ISSUE TITLE
How can I delete a "stuck" source file?

### ISSUE THREAD

**Issue by philiphinton** [gbif/ipt#1440]
I have what appears to be a corrupted source data file in my Source file list. It is a Excel file rather than a CSV, so that may be the problem. 

I cannot delete it; clicking the Edit button either puts the browser into a permanent loading mode (Chrome), or a screen like this (I.E. 11):
![failed to remove resource - unable to delete file 20190129 ento ie](https://user-images.githubusercontent.com/37783250/51881730-0e893e80-23e1-11e9-9ae5-3d8050d710b4.JPG)

Therefore, I tried deleting the entire Resource, only to get the following Error messages:
> "Unable to delete file: C:\IPT\resources\ento\sources\0818gbifentomology20181102.xls"
> "Failed to remove resource."

I tried the Delete button several times, getting the "Are you sure?" message each time, but to no avail.

### How can I delete the file itself? 
It appears in two Resources, as below. It shouldn't be in Botany, but that's probably my fault ... .

**Resources:**
http://ipt.aucklandmuseum.com:8080/ipt/manage/resource?r=ento
http://ipt.aucklandmuseum.com:8080/ipt/manage/resource.do?r=botany

**GBIF version:**
IPT Version 2.3.5-rb9b0544

**OS:**
Window 7 Professional

**Browser:**
_Chrome Version 57.0.2987.133 (64-bit)
Internet Explorer 11_

**Screenshots:**
![failed to remove resource - unable to delete file 20190129](https://user-images.githubusercontent.com/37783250/51872225-952c2480-23bd-11e9-993d-cfb3ac8a0076.JPG)

![failed to remove resource - unable to delete file 20190129 botany](https://user-images.githubusercontent.com/37783250/51881276-69219b00-23df-11e9-8d80-46b022300f17.JPG)

**Possibly related issues:**
https://github.com/gbif/ipt/issues/952

**Comment by philiphinton** [comment]
**The FreeMarker template error code is:**

FreeMarker template error (HTML_DEBUG mode; use RETHROW in production!)
Java method "org.gbif.ipt.model.ExcelFileSource.sheets()" threw an exception when invoked on org.gbif.ipt.model.ExcelFileSource object "ExcelFileSource[0818gbifentomology20181102;Resource ento]"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #macro select name options value="" i...  [in template "WEB-INF/pages/macros/forms.ftl" in macro "select" at line 37, column 1]
	- Reached through: @select name="source.sheetIdx" option...  [in template "WEB-INF/pages/manage/source.ftl" at line 128, column 17]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289)
	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:252)
	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:74)
	at freemarker.core.MethodCall._eval(MethodCall.java:65)
	at freemarker.core.Expression.eval(Expression.java:81)
	at freemarker.core.Environment.setMacroContextLocalsFromArguments(Environment.java:752)
	at freemarker.core.Environment.invoke(Environment.java:701)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
	at freemarker.core.Environment.visit(Environment.java:326)
	at freemarker.core.Environment.visit(Environment.java:332)
	at freemarker.core.Environment.visit(Environment.java:332)
	at freemarker.core.Environment.visit(Environment.java:332)
	at freemarker.core.Environment.process(Environment.java:305)
	at freemarker.template.Template.process(Template.java:378)
	at org.apache.struts2.views.freemarker.FreemarkerResult.doExecute(FreemarkerResult.java:223)
	at org.apache.struts2.dispatcher.StrutsResultSupport.execute(StrutsResultSupport.java:191)
	at com.opensymphony.xwork2.DefaultActionInvocation.executeResult(DefaultActionInvocation.java:372)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:276)
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:168)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.gbif.ipt.struts2.CsrfLoginInterceptor.intercept(CsrfLoginInterceptor.java:68)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:265)
	at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:76)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:73)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:125)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:91)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:140)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:119)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.gbif.ipt.struts2.RequireManagerInterceptor.intercept(RequireManagerInterceptor.java:91)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:84)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:41)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54)
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:575)
	at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81)
	at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by philiphinton** [comment]
**The Source Data Analyse button gives this:**

HTTP Status 500 - Method "execute" failed for object org.gbif.ipt.action.manage.SourceAction@5c48308d


type Exception report

message Method "execute" failed for object org.gbif.ipt.action.manage.SourceAction@5c48308d

description The server encountered an internal error that prevented it from fulfilling this request.

exception 
ognl.MethodFailedException: Method "execute" failed for object org.gbif.ipt.action.manage.SourceAction@5c48308d [java.lang.OutOfMemoryError: Java heap space]
	ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1311)
	ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:117)
	com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:108)
	ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1375)
	ognl.ASTMethod.getValueBody(ASTMethod.java:91)
	ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	ognl.SimpleNode.getValue(SimpleNode.java:258)
	ognl.Ognl.getValue(Ognl.java:470)
	ognl.Ognl.getValue(Ognl.java:434)
	com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:362)
	com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:414)
	com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:360)
	com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:430)
	com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:290)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:251)
	com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:168)
	com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.gbif.ipt.struts2.CsrfLoginInterceptor.intercept(CsrfLoginInterceptor.java:68)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:265)
	org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:76)
	com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229)
	com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229)
	com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:73)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:125)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:91)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:140)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:119)
	com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.gbif.ipt.struts2.RequireManagerInterceptor.intercept(RequireManagerInterceptor.java:91)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:84)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:41)
	com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:216)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:575)
	org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81)
	org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)



root cause 
java.lang.OutOfMemoryError: Java heap space



note The full stack trace of the root cause is available in the Apache Tomcat/7.0.64 logs.


Apache Tomcat/7.0.64

**Comment by MattBlissett** [comment]
I think I saw this once before; it's a bug in reading some Excel spreadsheets which overflows memory and prevents the page being displayed.

I'm going on holiday tomorrow, but @ManonGros or another of my colleagues can help if this workaround is too technical. They would need a username and password sent to helpdesk@gbif.org.

Last time, I didn't have direct access to the server. I added an additional  file to the resource, then opened the web browser "Developer Tools", network tab.  Deleting the extra file made a POST request when clicking "Yes" to confirm, which looks like this if "Copy as CURL" is chosen from the network tab:

`curl 'https://ipt.gbif.org/manage/source.do' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Cookie: JSESSIONID=4C1XXXXXXXXXXXXXXXXXXXXX; CSRFtoken=dDn7ov3vXxXXxXxxXxXXxxxxQt' --data 'r=africancranesightings&id=datapaper_cranesightings_20160128_gbif&source.name=datapaper_cranesightings_20160128_gbif&source.ignoreHeaderLines=1&source.sheetIdx=0&source.multiValueFieldsDelimitedBy=&delete=Delete+source+file'`

(There are more headers, I've removed the ones that aren't necessary for brevity.) It's possible then to edit the name of the resource and issue the request using curl.

It might be OK to delete the file from the server and replace it with another (e.g. an empty spreadsheet), but I haven't tested that.

**Comment by philiphinton** [comment]
Thanks Matt.
I followed your instructions beautifully right up to "issue the request using curl". I don't know how to do that, but I'll investigate it.
Failing that I'll contact helpdesk@gbif.org.

**This is the cURL report I got, with the file name changed to suit:**
curl "http://ipt.aucklandmuseum.com:8080/ipt/manage/source.do" -H "Cookie: JSESSIONID=766CF0F1FCD37F161195FAAC83BAAC8D; CSRFtoken=ybCPFq011a9xPCDsNRqMttOY4s4GdzYk; _gcl_au=1.1.1145635461.1546989003; _ga=GA1.2.868766286.1546989003; __utmt_gbif=1; __utma=215038927.868766286.1546989003.1548730688.1548796112.4; __utmb=215038927.5.10.1548796112; __utmc=215038927; __utmz=215038927.1547781821.1.1.utmcsr=(direct)^|utmccn=(direct)^|utmcmd=(none)" -H "Origin: http://ipt.aucklandmuseum.com:8080" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: en-US,en;q=0.8" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Mobile Safari/537.36" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cache-Control: max-age=0" -H "Referer: http://ipt.aucklandmuseum.com:8080/ipt/manage/source.do?r=ento^&id=0818gbifentomology20181102" -H "Connection: keep-alive" --data "r=ento^&id=0818gbifentomology20181102^&source.name=0818gbifentomology20181102^&source.ignoreHeaderLines=1^&fileSource.fieldsTerminatedByEscaped=^%^5Ct^&fileSource.fieldsEnclosedByEscaped=^&source.multiValueFieldsDelimitedBy=^%^7C^&source.encoding=UTF-16LE^&source.dateFormat=DD-MM-YYYY^&delete=Delete+source+file" --compressed

**Comment by philiphinton** [comment]
Hi folk,
I sent the email below to helpdesk@gbif.org a few days ago: I've not had a reply so I'm just wondering how the solution is going...

"Hi all,
Matt’s statement “…issue the request using curl.” is beyond my current skill, I’m afraid.
Using <my email address> and <a temporary password" could someone help me with removing a problem file and document how this is done (so I can do it for another resource with the same problem), please?
Here is the ticket: https://github.com/gbif/ipt/issues/1440
Thanks,
Phil"

**Comment by ManonGros** [comment]
Hi @philiphinton sorry for the delay, I think that we managed to delete your stuck files, thanks for sending us the credentials!
I will close the issue now but let us know if you need anything else.

**Comment by philiphinton** [comment]
Thanks for doing that Marie!
Would you tell me how it is done, please? (or does one have to be a super admin? 😊)

Thanks,
Phil

Phil Hinton B.Hort.(Tech)(Hons) | CIA Collections Data Analyst | Kaitātari Raraunga Kohikohinga | Auckland War Memorial Museum | Tamaki Paenga Hira | The Domain, Private Bag 92018, Victoria Street West, Auckland 1142, New Zealand |  www.aucklandmuseum.com<http://www.aucklandmuseum.com/> | M 021 0204 7323 | P +64 9 309 0443 ext 7341 | F +64 9 379 9956 | E PHinton@aucklandmuseum.com

**Comment by ManonGros** [comment]
Actually, you were almost done :)
We essentially followed Matt's instruction:
1) Log as admin in your IPT.
2) Find your blocked file and click on it.
3) Open the web browser "Developer Tools" and click on the network tab
4) There is essentially one object in the network tab, right click and "Copy as CURL"
5) This gives you a CURL request which contains a `JSESSIONID` and a `CSRFtoken`.
6) Take Matt's CURL request an replace the values for `JSESSIONID`, `CSRFtoken`, `r`, `id`, `source.name` and the URL by your own values:
```
curl 'http://ipt.aucklandmuseum.com:8080/ipt/manage/source.do' 
    -H 'Content-Type: application/x-www-form-urlencoded' 
    -H 'Cookie: JSESSIONID=993XXXXXXXXXXXXXXXXXXXXXXXXXXXXX; CSRFtoken=e1cxxxXxxXxXXXxXxXXxXXXxxXxXXXXX' 
   --data 'r=ento&id=0818gbifentomology20181102&source.name=0818gbifentomology20181102&source.ignoreHeaderLines=1&source.sheetIdx=0&source.multiValueFieldsDelimitedBy=&delete=Delete+source+file'
```
7) Paste that into a terminal.
8) If you don't get any error message, you should be good.

**Comment by philiphinton** [comment]
Oh, so close!
Thanks for that Marie; we should be able to do that ourselves if the situation arises again.
Cheers,
Phil

Phil Hinton B.Hort.(Tech)(Hons) | CIA Collections Data Analyst | Kaitātari Raraunga Kohikohinga | M 021 0204 7323 | P ext 7341 | E phinton@aucklandmuseum.com<mailto:phinton@aucklandmuseum.com> | L The Hub

**Comment by philiphinton** [comment]
Oh, so close!
Thanks for that Marie; we should be able to do that ourselves if the situation arises again.
Cheers,
Phil
