### ISSUE TITLE
NullPointerException in PublishingMonitor's monitor thread - IPT 2.3.6

### ISSUE THREAD

**Issue by YasuhikoFujita** [gbif/ipt#1449]
IPT 2.3.6 (with struts2 2.5.14.1) PublishingMonitor's monitor thread always crashes with NullPointerException, on auto publishing.  IPT 2.3.5 was OK.
```
Exception in thread "Thread-3" java.lang.NullPointerException
        at com.opensymphony.xwork2.ActionSupport.getContainer(ActionSupport.java:307)
        at com.opensymphony.xwork2.ActionSupport.getLocaleProvider(ActionSupport.java:295)
        at com.opensymphony.xwork2.ActionSupport.getLocale(ActionSupport.java:73)
        at org.gbif.ipt.struts2.SimpleTextProvider.getText(SimpleTextProvider.java:89)
        at org.gbif.ipt.action.BaseAction.getText(BaseAction.java:211)
        at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.isLocked(ResourceManagerImpl.java:856)
        at org.gbif.ipt.config.PublishingMonitor$QueueMonitor.run(PublishingMonitor.java:72)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rukayaj** [comment]
@jlegind and also @timrobertson100: we spoke briefly about Norwegian University of Science and Technology / NTNU's IPT failing to autopublish datasets - I think this is what is causing it. GBIF Norway's IPT also stopped auto publishing when I upgraded it to 2.3.6, going back to 2.3.5 fixed it.

**Comment by MattBlissett** [comment]
Thanks for the fix Yasuhiko, this will very soon be merged into master.
