### ISSUE TITLE
After version update 2.3.4 ->2.4.2: manage/resource edit no longer works

### ISSUE THREAD

**Issue by esko-piirainen** [gbif/ipt#1568]
Navigating
Manage Resources > select one of the resources > source data: edit  > ipt/manage/source.do?r=ipt_feeder&id=xxx

Stacktrace:
```
FreeMarker template error (HTML_DEBUG mode; use RETHROW in production!)


The following has evaluated to null or missing:
==> source.rdbms  [in template "WEB-INF/pages/manage/source.ftl" at line 89, column 68]

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #macro select name options value="" i...  [in template "WEB-INF/pages/macros/forms.ftl" in macro "select" at line 37, column 1]
	- Reached through: @select name="rdbms" options=jdbcOpti...  [in template "WEB-INF/pages/manage/source.ftl" at line 89, column 17]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	[...]
	at org.apache.struts2.views.freemarker.FreemarkerResult.doExecute(FreemarkerResult.java:184)
	at org.apache.struts2.result.StrutsResultSupport.execute(StrutsResultSupport.java:206)
[...]	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:263)
	at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:49)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
[...]

```

resource.xml

```
<resource>
  <coreType>OCCURRENCE</coreType>
  <subtype>observation</subtype>
  <updateFrequency>MONTHLY</updateFrequency>
  <status>REGISTERED</status>
  <publicationMode>AUTO_PUBLISH_ON</publicationMode>
  <citationAutoGenerated>false</citationAutoGenerated>
  <emlVersion>1.11</emlVersion>
  <replacedEmlVersion>1.10</replacedEmlVersion>
  <lastPublished>2021-03-19 08:38:28.291 UTC</lastPublished>
  <nextPublished>2021-04-18 07:38:28.291 UTC</nextPublished>
  <recordsPublished>1401148</recordsPublished>
  <recordsByExtension>
    <entry>
      <string>http://rs.tdwg.org/dwc/terms/Occurrence</string>
      <int>1401148</int>
    </entry>
  </recordsByExtension>
  <key>a4d53b24-d61b-4ee5-addd-8b42d54a913f</key>
  <organisation>04fd2e13-6881-4e5c-9dd1-8fdd9ab993c1</organisation>
  <creator>XXXX@helsinki.fi</creator>
  <created>2017-09-05 11:47:32.942 UTC</created>
  <modifier reference="../creator"/>
  <modified>2021-04-29 10:11:29.838 UTC</modified>
  <metadataModified>2019-02-20 12:23:50.103 UTC</metadataModified>
  <mappingsModified>2019-02-20 12:27:22.466 UTC</mappingsModified>
  <sourcesModified>2020-12-18 08:40:31.624 UTC</sourcesModified>
  <managers/>
  <sources>
    <sqlsource>
      <resource reference="../../.."/>
      <name>vertica</name>
      <encoding>UTF-8</encoding>
      <multiValueFieldsDelimitedBy></multiValueFieldsDelimitedBy>
      <dateFormat>YYYY-MM-DD</dateFormat>
      <columns>13</columns>
      <readable>true</readable>
      <sql>SELECT * FROM GBIF_IPT.IPT_WINTERBIRD</sql>
      <host>XXXX</host>
      <database>XXXX</database>
      <username>GBIF_IPT</username>
      <password>XXXX</password>
    </sqlsource>
  </sources>
  <mappings>
    <mapping>
      <source class="sqlsource" reference="../../../sources/sqlsource"/>
      <extension>http://rs.tdwg.org/dwc/terms/Occurrence</extension>
      <fields class="sorted-set">
        <field>
          <index>1</index>
          <term>http://rs.tdwg.org/dwc/terms/basisOfRecord</term>
          <type>string</type>
        </field>
        <field>
          <index>6</index>
          <term>http://rs.tdwg.org/dwc/terms/class</term>
          <type>string</type>
        </field>
        <field>
          <index>10</index>
          <term>http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters</term>
          <type>string</type>
        </field>
        <field>
          <index>11</index>
          <term>http://rs.tdwg.org/dwc/terms/country</term>
          <type>string</type>
        </field>
        <field>
          <index>7</index>
          <term>http://rs.tdwg.org/dwc/terms/decimalLatitude</term>
          <type>string</type>
        </field>
        <field>
          <index>8</index>
          <term>http://rs.tdwg.org/dwc/terms/decimalLongitude</term>
          <type>string</type>
        </field>
        <field>
          <index>3</index>
          <term>http://rs.tdwg.org/dwc/terms/eventDate</term>
          <type>string</type>
        </field>
        <field>
          <index>9</index>
          <term>http://rs.tdwg.org/dwc/terms/geodeticDatum</term>
          <type>string</type>
        </field>
        <field>
          <index>12</index>
          <term>http://rs.tdwg.org/dwc/terms/individualCount</term>
          <type>string</type>
        </field>
        <field>
          <index>5</index>
          <term>http://rs.tdwg.org/dwc/terms/kingdom</term>
          <type>string</type>
        </field>
        <field>
          <index>0</index>
          <term>http://rs.tdwg.org/dwc/terms/occurrenceID</term>
          <defaultValue></defaultValue>
          <type>string</type>
        </field>
        <field>
          <index>2</index>
          <term>http://rs.tdwg.org/dwc/terms/scientificName</term>
          <type>string</type>
        </field>
        <field>
          <index>4</index>
          <term>http://rs.tdwg.org/dwc/terms/taxonRank</term>
          <type>string</type>
        </field>
      </fields>
      <idColumn>0</idColumn>
      <idSuffix></idSuffix>
      <filter>
        <param></param>
        <filterTime>AfterTranslation</filterTime>
      </filter>
      <doiUsedForDatasetId>false</doiUsedForDatasetId>
      <lastModified reference="../../../mappingsModified"/>
    </mapping>
  </mappings>
  <versionHistory class="linked-list">
    <versionhistory>
       [...]
  </versionHistory>
  <identifierStatus>UNRESERVED</identifierStatus>
</resource>
```

**Comment by esko-piirainen** [comment]
@MattBlissett Hi! We actually tried to revert back to 2.3.4, but that did not fix the issue. So I don't know what has happened to the SQL datasource definition, but we can't use the UI to fix it. It was perhaps unrelated to the version update (or not)..

**Comment by mike-podolskiy90** [comment]
Thank you for filing the issue @esko-piirainen 
There is no `rdbms` tag inside `sqlSource`. I suspect that might be the issue.

**Comment by esko-piirainen** [comment]
Ok! I managed to fix this by manually modifying the `resource.xml` and adding
```
<rdms>vertica</rdms>
```
to each of our resources.

There is some kind of bug that the rdms is dropped out from the `resource.xml`  when deploying a newer version of IPT and not adding the rdms to `jdbc.properties`

So we have a custom rdms that after each deploy of IPT war we must manually edit in: `/WEB-INF/classes/jdbc.properties`:
```
# Vertica driver
vertica.title=Vertica
vertica.driver=com.vertica.jdbc.Driver
vertica.url=jdbc:vertica://{host}/{database}
vertica.limitType=LIMIT
```
