### ISSUE TITLE
NullPointerException when defining a database connection

### ISSUE THREAD

**Issue by ben3000** [gbif/ipt#1645]
After configuring a PostgreSQL database connection, I get the following NPE:

<pre>
java.lang.NullPointerException
	at org.gbif.ipt.model.Resource.addSource(Resource.java:203)
	at org.gbif.ipt.action.manage.SourceAction.save(SourceAction.java:415)
	at org.gbif.ipt.action.POSTAction.execute(POSTAction.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
</pre>

The logs also show this exception, which looks relevant:

<pre>
ERROR 02-Sep-2021 08:21:53 [com.opensymphony.xwork2.conversion.impl.InstantiatingNullHandler] - Could not create and/or set value back on to object
com.opensymphony.xwork2.util.reflection.ReflectionException: null
	at com.opensymphony.xwork2.ognl.OgnlReflectionProvider.setValue(OgnlReflectionProvider.java:139) ~[struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.conversion.impl.InstantiatingNullHandler.nullPropertyValue(InstantiatingNullHandler.java:130) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.ognl.OgnlNullHandlerWrapper.nullPropertyValue(OgnlNullHandlerWrapper.java:39) [struts2-core-2.5.17.jar:2.5.17]
	at ognl.ASTProperty.getValueBody(ASTProperty.java:118) [ognl-3.1.15.jar:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) [ognl-3.1.15.jar:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) [ognl-3.1.15.jar:?]
	at ognl.ASTChain.setValueBody(ASTChain.java:222) [ognl-3.1.15.jar:?]
	at ognl.SimpleNode.evaluateSetValueBody(SimpleNode.java:220) [ognl-3.1.15.jar:?]
	at ognl.SimpleNode.setValue(SimpleNode.java:301) [ognl-3.1.15.jar:?]
	at ognl.Ognl.setValue(Ognl.java:713) [ognl-3.1.15.jar:?]
	at com.opensymphony.xwork2.ognl.OgnlUtil$1.execute(OgnlUtil.java:345) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.ognl.OgnlUtil$1.execute(OgnlUtil.java:337) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecute(OgnlUtil.java:432) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.ognl.OgnlUtil.setValue(OgnlUtil.java:337) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.ognl.OgnlValueStack.trySetValue(OgnlValueStack.java:188) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.ognl.OgnlValueStack.setValue(OgnlValueStack.java:175) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.ognl.OgnlValueStack.setParameter(OgnlValueStack.java:157) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.setParameters(ParametersInterceptor.java:211) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:129) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:137) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:67) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:133) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:89) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:175) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:119) [classes/:?]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:85) [classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:41) [classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) [guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79) [struts2-core-2.5.17.jar:2.5.17]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141) [struts2-core-2.5.17.jar:2.5.17]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.2.0.jar:?]
	at org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:23) [classes/:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133) [guice-servlet-4.2.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.70]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196) [catalina.jar:8.5.70]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:8.5.70]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544) [catalina.jar:8.5.70]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:8.5.70]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.70]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698) [catalina.jar:8.5.70]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:8.5.70]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:364) [catalina.jar:8.5.70]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:624) [tomcat-coyote.jar:8.5.70]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.70]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831) [tomcat-coyote.jar:8.5.70]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1650) [tomcat-coyote.jar:8.5.70]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.70]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:8.5.70]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:8.5.70]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.70]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: ognl.NoSuchPropertyException: org.gbif.ipt.action.manage.SourceAction.sqlSource
	at ognl.ObjectPropertyAccessor.setProperty(ObjectPropertyAccessor.java:166) ~[ognl-3.1.15.jar:?]
	at com.opensymphony.xwork2.ognl.accessor.ObjectAccessor.setProperty(ObjectAccessor.java:42) ~[struts2-core-2.5.17.jar:2.5.17]
	at ognl.OgnlRuntime.setProperty(OgnlRuntime.java:2686) ~[ognl-3.1.15.jar:?]
	at ognl.ASTProperty.setValueBody(ASTProperty.java:127) ~[ognl-3.1.15.jar:?]
	at ognl.SimpleNode.evaluateSetValueBody(SimpleNode.java:220) ~[ognl-3.1.15.jar:?]
	at ognl.SimpleNode.setValue(SimpleNode.java:301) ~[ognl-3.1.15.jar:?]
	at ognl.Ognl.setValue(Ognl.java:713) ~[ognl-3.1.15.jar:?]
	at ognl.Ognl.setValue(Ognl.java:759) ~[ognl-3.1.15.jar:?]
	at com.opensymphony.xwork2.ognl.OgnlReflectionProvider.setValue(OgnlReflectionProvider.java:137) ~[struts2-core-2.5.17.jar:2.5.17]
	... 85 more
</pre>

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue @ben3000 
We'll check that out

**Comment by mike-podolskiy90** [comment]
Fix to this will be included in the next 2.5.1 release
Closing this
