### ISSUE TITLE
NPE upon trying to publish a resource

### ISSUE THREAD

**Issue by meliezer** [gbif/ipt#1649]
It happens for a specific dataset, but I don't know what is the problem. I could reproduce it in https://ipt.gbif.org upon need so you'll see the source files and related mapping.
IPT 2.5.1 under Tomcat 9, Debian.

Stack without debug:
Start writing data file for Darwin Core Occurrence
No lines were skipped due to errors for mapping Darwin Core Occurrence in source occurrence
No lines were skipped due to errors for mapping Darwin Core Occurrence in source occurrence
No lines with fewer columns than mapped for mapping Darwin Core Occurrence in source occurrence
All lines match the filter criteria for mapping Darwin Core Occurrence in source occurrence
Data file written for Darwin Core Occurrence with 21605 records and 10 columns
Archive generation failed!
java.lang.NullPointerException
	at org.gbif.ipt.task.GenerateDwca.addFieldsToArchive(GenerateDwca.java:1422)
	at org.gbif.ipt.task.GenerateDwca.addDataFile(GenerateDwca.java:144)
	at org.gbif.ipt.task.GenerateDwca.createDataFiles(GenerateDwca.java:1036)
	at org.gbif.ipt.task.GenerateDwca.call(GenerateDwca.java:932)
	at org.gbif.ipt.task.GenerateDwca.call(GenerateDwca.java:43)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Stack with debug info:
Exception
org.gbif.ipt.service.manage.impl.ResourceManagerImpl.isLocked(ResourceManagerImpl.java:887)
org.gbif.ipt.service.manage.impl.ResourceManagerImpl.isLocked(ResourceManagerImpl.java:906)
org.gbif.ipt.service.manage.impl.ResourceManagerImpl.status(ResourceManagerImpl.java:2203)
org.gbif.ipt.action.manage.OverviewAction.updateReport(OverviewAction.java:1085)
org.gbif.ipt.action.manage.OverviewAction.prepare(OverviewAction.java:1006)
com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167)
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196)
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121)
com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48)
org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574)
org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141)
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:23)
com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:415)
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java.base/java.lang.Thread.run(Thread.java:829)

**Comment by meliezer** [comment]
Adding also a log line which helped me understanding:
ERROR 07-Sep-2021 08:55:23 [org.gbif.ipt.model.Resource] - ExtensionMapping referencing NULL Extension or Source for resource: dummy_dataset_please_ignore

Resolved. I had an unfinished mapping in which I haven't defined the source file. Then I restarted the mapping, but the old one remained:
Extended Measurement Or Facts	0 terms mapped to . 6 Sep 2021, 14:59:09
and of course the mapping preview fails: "Mapping preview failed".

I simply removed it and all is OK now!
