### ISSUE TITLE
Error when editing metadata

### ISSUE THREAD

**Issue by lisasundqvist** [gbif/ipt#1916]
I got this error when I wanted to edit the metadata

java.lang.NullPointerException
	at org.gbif.ipt.action.manage.MetadataAction.loadAgentVocabularies(MetadataAction.java:754)
	at org.gbif.ipt.action.manage.MetadataAction.prepare(MetadataAction.java:286)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167)

**Comment by mike-podolskiy90** [comment]
@lisasundqvist Thank you for reporting the issue.
What is your IPT version please?

**Comment by mike-podolskiy90** [comment]
I guess you're using v2.5.1 or lower. If so, please update your IPT to the most recent version (currently v2.6.3), I believe the issue similar to yours was fixed last year.

**Comment by mike-podolskiy90** [comment]
You're welcome. Anyway, I strongly recommend you to update your IPT, versions prior 2.5.8 have critical security issues.
