### ISSUE TITLE
ColDP publication fails for name relations

### ISSUE THREAD

**Issue by mdoering** [gbif/ipt#2012]
https://ipt3.gbif-uat.org/publicationlog.do?r=donaldscoldp
> Publishing version #1.0 of resource donaldscoldp failed: Archive generation for resource donaldscoldp failed: Error adding schema file

Logs:
> Data package generation started for version #1.0
Start writing data file for name
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source name
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source name
No lines with fewer columns than mapped for mapping Catalogue of Life Data Package in source name
All lines match the filter criteria for mapping Catalogue of Life Data Package in source name
Data file written for name with 486 records and 20 columns
Start writing data file for names-relation
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source namerelation
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source namerelation
No lines with fewer columns than mapped for mapping Catalogue of Life Data Package in source namerelation
All lines match the filter criteria for mapping Catalogue of Life Data Package in source namerelation

**Comment by mdoering** [comment]
When I remove the name relations I get another unclear problem:

>Data package generation started for version #1.0
Start writing data file for name
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source name
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source name
No lines with fewer columns than mapped for mapping Catalogue of Life Data Package in source name
All lines match the filter criteria for mapping Catalogue of Life Data Package in source name
Data file written for name with 486 records and 20 columns
Start writing data file for reference
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source reference
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source reference
No lines with fewer columns than mapped for mapping Catalogue of Life Data Package in source reference
All lines match the filter criteria for mapping Catalogue of Life Data Package in source reference
Data file written for reference with 158 records and 25 columns
Start writing data file for species-interaction
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source speciesinteraction
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source speciesinteraction
No lines with fewer columns than mapped for mapping Catalogue of Life Data Package in source speciesinteraction
All lines match the filter criteria for mapping Catalogue of Life Data Package in source speciesinteraction
Data file written for species-interaction with 3 records and 7 columns
Start writing data file for synonym
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source synonym
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source synonym
No lines with fewer columns than mapped for mapping Catalogue of Life Data Package in source synonym
All lines match the filter criteria for mapping Catalogue of Life Data Package in source synonym
Data file written for synonym with 196 records and 10 columns
Start writing data file for taxon
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source taxon
No lines were skipped due to errors for mapping Catalogue of Life Data Package in source taxon
No lines with fewer columns than mapped for mapping Catalogue of Life Data Package in source taxon
All lines match the filter criteria for mapping Catalogue of Life Data Package in source taxon
Data file written for taxon with 288 records and 34 columns
All data files completed
Metadata added
Data package generation failed!
io.frictionlessdata.tableschema.exception.InvalidCastException: io.frictionlessdata.tableschema.exception.TypeInferringException
	at io.frictionlessdata.tableschema.field.Field.castValue(Field.java:288)
	at io.frictionlessdata.tableschema.field.Field.castValue(Field.java:302)
	at io.frictionlessdata.tableschema.iterator.TableIterator.next(TableIterator.java:100)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at io.frictionlessdata.tableschema.Table.writeCSVData(Table.java:715)
	at io.frictionlessdata.tableschema.Table.writeCsv(Table.java:459)
	at io.frictionlessdata.tableschema.Table.write(Table.java:483)
	at io.frictionlessdata.tableschema.Table.writeCsv(Table.java:510)
	at io.frictionlessdata.datapackage.resource.AbstractResource.writeData(AbstractResource.java:591)
	at io.frictionlessdata.datapackage.Package.write(Package.java:555)
	at org.gbif.ipt.task.GenerateDataPackage.bundleArchive(GenerateDataPackage.java:231)
	at org.gbif.ipt.task.GenerateDataPackage.call(GenerateDataPackage.java:133)
	at org.gbif.ipt.task.GenerateDataPackage.call(GenerateDataPackage.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.frictionlessdata.tableschema.exception.TypeInferringException
	at io.frictionlessdata.tableschema.field.DateField.parseValue(DateField.java:59)
	at io.frictionlessdata.tableschema.field.DateField.parseValue(DateField.java:16)
	at io.frictionlessdata.tableschema.field.Field.castValue(Field.java:266)
	... 16 more

**Comment by mike-podolskiy90** [comment]
I've updated ColDP schemas recently (in rs.gbif.org), https://github.com/gbif/rs.gbif.org/commit/a069d8188c08d3e0134e359e6290bdd22b46ee93

We need to re-install schemas in the IPT
