### ISSUE TITLE
Old published resources without an organization in resource.xml crash the IPT during loading.

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#2025]
In version 2.6.3, when a resource has been published but doesn't have an organization in resource.xml, other resources are loaded and a warning shown: 

![image](https://github.com/gbif/ipt/assets/583320/597db816-a327-428c-bb83-bba9e27d8e27)

This can happen with resources last published before v2.2 (March 2015); I don't know the background for why this might have been necessary.

Starting in version 2.7.0, the IPT stops loading at this point without logging any error, so only some resources (depending on the order in the directory) are loaded.  Visiting /setup.do does show the stack trace:

```
Caused by: java.lang.IllegalArgumentException: Failed to reconstruct resource version because not all of organisation, version history, or version eml file were provided
	at org.gbif.ipt.utils.ResourceUtils.reconstructVersion(ResourceUtils.java:65)
	at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.toSimplifiedResourceReconstructedVersion(ResourceManagerImpl.java:271)
	at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.addResource(ResourceManagerImpl.java:254)
	at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.load(ResourceManagerImpl.java:1539)
	at org.gbif.ipt.service.admin.impl.ConfigManagerImpl.loadDataDirConfig(ConfigManagerImpl.java:233)
	at org.gbif.ipt.service.admin.impl.ConfigManagerImpl.<init>(ConfigManagerImpl.java:90)
	at org.gbif.ipt.service.admin.impl.ConfigManagerImpl$$FastClassByGuice$$39b45602.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
```

and adding a log statement before this exception is thrown shows it is organization that's missing.

I think this is because this try-catch block accommodating resources last published before v2.2 (March 2015) has gone: https://github.com/gbif/ipt/commit/647b80179582ca6d1c5f0cf2d600dc749879849c#diff-9cdea1d2cd4e8f47aba1c7add95b76ef315f2f473fbdacf6568d9a68a644c4bdL76-L96

**Comment by MattBlissett** [comment]
Mikhail; this was an old, test dataset.  Depending who was first to log in to the IPT, it could be that the warning has gone unnoticed for years.  This can be a low priority (or maybe no priority at all) unless we see other cases, it should be very unusual.

**Comment by mike-podolskiy90** [comment]
Thanks Matt. This is something that we have to address in the next version. It silently swallows exception and does not load any resources after the exception.
