### ISSUE TITLE
Hi im having a problem with my minecraft server, please can someone help me i don't know what to do

### ISSUE THREAD

**Issue by Kteams5467** [gbif/ipt#2052]
today i tried to open my minecraft server as usual, wich by the way 1 week ago opened without any issues, and i got this error:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 18/06/23 16.00
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.34.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.34.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.34.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115) ~[log4j-core-2.15.0.jar:2.15.0] {}
-- MOD aequivaleo --
Details:
	Mod File: aequivaleo-0.1.57-ALPHA-universal.jar
	Failure message: Aequivaleo (aequivaleo) has failed to load correctly
		java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory@2bd971d9] unable to create manager for [logs/aequivaleo/ingredient/error.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$FactoryData@762e62c4]
	Mod Version: 0.1.57-ALPHA
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory@2bd971d9] unable to create manager for [logs/aequivaleo/ingredient/error.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$FactoryData@762e62c4]
Stacktrace:
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115) ~[log4j-core-2.15.0.jar:2.15.0] {}
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100) ~[log4j-core-2.15.0.jar:2.15.0] {}
	at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:107) ~[log4j-core-2.15.0.jar:2.15.0] {}
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender$Builder.build(RollingRandomAccessFileAppender.java:132) ~[log4j-core-2.15.0.jar:2.15.0] {}
	at com.ldtteam.aequivaleo.recipe.equivalency.RecipeCalculatorLogHandler.lambda$setupLogging$0(RecipeCalculatorLogHandler.java:55) ~[aequivaleo:0.1.57-ALPHA] {re:classloading}
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_371] {}
	at com.ldtteam.aequivaleo.recipe.equivalency.RecipeCalculatorLogHandler.setupLogging(RecipeCalculatorLogHandler.java:33) ~[aequivaleo:0.1.57-ALPHA] {re:classloading}
	at com.ldtteam.aequivaleo.Aequivaleo.<init>(Aequivaleo.java:33) ~[aequivaleo:0.1.57-ALPHA] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_371] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_371] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_371] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_371] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_371] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_371] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_371] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_371] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_371] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_371] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_371] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_371, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3878233624 bytes (3698 MB) / 4211605504 bytes (4016 MB) up to 4211605504 bytes (4016 MB)
	CPUs: 6
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.17.0
	Mod List: 
		mowziesmobs-1.5.23.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.23              |CREATE_REG|Manifest: NOSIGNATURE
		Tropicraft-9.2.0-release+90.jar                   |Tropicraft                    |tropicraft                    |9.2.0-release+90    |CREATE_REG|Manifest: NOSIGNATURE
		ogres-0.3.jar                                     |ogres                         |ogres                         |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		minecraft-comes-alive-7.0.11-forge.jar            |Minecraft Comes Alive         |mca                           |7.0.11              |CREATE_REG|Manifest: NOSIGNATURE
		EasyMagic-v1.0.4-1.16.5.jar                       |Easy Magic                    |easymagic                     |1.0.4               |CREATE_REG|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.16.5-7.7.1.145.jar                          |Just Enough Items             |jei                           |7.7.1.145           |CREATE_REG|Manifest: NOSIGNATURE
... (51 righe a disposizione)

**Comment by MattBlissett** [comment]
Hi,

I'm not sure what led you here, but this repository is for software developed by the Global Biodiversity Information Facility, see https://www.gbif.org.

I think you need to ask at https://forums.minecraftforge.net/forum/18-support-bug-reports/
