### ISSUE TITLE
IPT does not allow to reserve a DOI for a new non-published resource

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2116]
Should we allow this?

**Comment by mike-podolskiy90** [comment]
Stacktrace
```
ERROR 04-Oct-2023 12:42:27 [org.gbif.ipt.action.manage.OverviewAction] - Failed to reserve *** because DOI metadata was invalid: DataCite schema (v4) requires the publication year
org.gbif.doi.service.InvalidMetadataException: DataCite schema (v4) requires the publication year
	at org.gbif.ipt.utils.DataCiteMetadataBuilder.getPublicationYear(DataCiteMetadataBuilder.java:395) ~[DataCiteMetadataBuilder.class:?]
	at org.gbif.ipt.utils.DataCiteMetadataBuilder.createDataCiteMetadata(DataCiteMetadataBuilder.java:103) ~[DataCiteMetadataBuilder.class:?]
	at org.gbif.ipt.action.manage.OverviewAction.doReserveDOI(OverviewAction.java:981) ~[OverviewAction.class:?]
	at org.gbif.ipt.action.manage.OverviewAction.reserveDoi(OverviewAction.java:877) ~[OverviewAction.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at ognl.OgnlRuntime.invokeMethodInsideSandbox(OgnlRuntime.java:1266) ~[ognl-3.1.29.jar:?]
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:1251) ~[ognl-3.1.29.jar:?]
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1969) ~[ognl-3.1.29.jar:?]
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) ~[ognl-3.1.29.jar:?]
	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:98) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:90) ~[struts2-core-2.5.31.jar:2.5.31]
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:2045) ~[ognl-3.1.29.jar:?]
	at ognl.ASTMethod.getValueBody(ASTMethod.java:97) ~[ognl-3.1.29.jar:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[ognl-3.1.29.jar:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[ognl-3.1.29.jar:?]
	at ognl.Ognl.getValue(Ognl.java:537) ~[ognl-3.1.29.jar:?]
	at ognl.Ognl.getValue(Ognl.java:501) ~[ognl-3.1.29.jar:?]
	at com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:492) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:544) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:490) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:438) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:293) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:254) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.gbif.ipt.struts2.RequireManagerInterceptor.intercept(RequireManagerInterceptor.java:138) ~[RequireManagerInterceptor.class:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:179) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.gbif.ipt.struts2.CsrfLoginInterceptor.intercept(CsrfLoginInterceptor.java:91) ~[CsrfLoginInterceptor.class:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:263) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:49) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.doIntercept(ConversionErrorInterceptor.java:142) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:140) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:140) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:67) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:133) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:89) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:175) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:134) ~[RedirectMessageInterceptor.class:?]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:106) ~[SetupAndCancelInterceptor.class:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:54) ~[ResourceSessionInterceptor.class:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37) ~[CorsFilter.class:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133) ~[guice-servlet-4.2.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) ~[catalina.jar:7.0.76]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) ~[catalina.jar:7.0.76]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) ~[catalina.jar:7.0.76]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) ~[catalina.jar:7.0.76]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:498) ~[catalina.jar:7.0.76]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) ~[catalina.jar:7.0.76]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) ~[catalina.jar:7.0.76]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) ~[catalina.jar:7.0.76]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) ~[catalina.jar:7.0.76]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) ~[catalina.jar:7.0.76]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) ~[tomcat-coyote.jar:7.0.76]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) ~[tomcat-coyote.jar:7.0.76]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) ~[tomcat-coyote.jar:7.0.76]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-coyote.jar:7.0.76]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
```

**Comment by mike-podolskiy90** [comment]
I suppose we should add a warning message that only published resources can have a DOI and prevent an exception from happening

**Comment by EstebanMH-SiB** [comment]
I am not entirely sure this error message is related, but I think so:

<img width="1920" height="392" alt="Image" src="https://github.com/user-attachments/assets/edb025b1-e2b9-4a47-9796-73fd6ebd2747" />

We have this problem happen a couple of times in our last IPT version 3.1.5, for example in this [resource](https://ipt.biodiversidad.co/sib/manage/resource.do?r=assa_compensacion_sucre) it shows the warning. We solve it by publishing a private version and after that reserving a DOI and it works after that.

However it is inconsistent, it does not happen in every dataset and we do not know in which ones will happen. As far as we know, it should let us reserve a DOI for a new resource without having to publish a private version.

**Comment by mike-podolskiy90** [comment]
The main problem is that without a publication date, DataCite does not allow you to register a DOI, and if the resource has not yet been published, it does not have a publication date. This should be clarified in the IPT manual.

**Comment by EstebanMH-SiB** [comment]
Would it be possible to fetch the current date when you click “Reserve DOI” as it was done before? As far as I can see, is almost the same as publishing a private version only for the EML file to have a publication date so you can reserve a DOI

**Comment by mike-podolskiy90** [comment]
Yes, it might be alright to do that
