### ISSUE TITLE
TypeInferringException when publishing Interaction DP

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2276]
IPT reports:

```
Publishing version #1.0 of resource uces-sib_zamia_incognita_pollination failed: Archive generation for resource uces-sib_zamia_incognita_pollination failed: io.frictionlessdata.tableschema.exception.InvalidCastException: io.frictionlessdata.tableschema.exception.TypeInferringException
```

Stacktrace:
```
io.frictionlessdata.tableschema.exception.InvalidCastException: io.frictionlessdata.tableschema.exception.TypeInferringException
	at io.frictionlessdata.tableschema.field.Field.castValue(Field.java:288)
	at io.frictionlessdata.tableschema.field.Field.castValue(Field.java:302)
	at io.frictionlessdata.tableschema.iterator.TableIterator.next(TableIterator.java:100)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at io.frictionlessdata.tableschema.Table.writeCSVData(Table.java:730)
	at io.frictionlessdata.tableschema.Table.writeCsv(Table.java:474)
	at io.frictionlessdata.tableschema.Table.write(Table.java:498)
	at io.frictionlessdata.tableschema.Table.writeCsv(Table.java:525)
	at io.frictionlessdata.datapackage.resource.AbstractResource.writeData(AbstractResource.java:591)
	at io.frictionlessdata.datapackage.Package.write(Package.java:557)
	at io.frictionlessdata.datapackage.Package.write(Package.java:525)
	at org.gbif.ipt.task.GenerateDataPackage.bundleArchive(GenerateDataPackage.java:235)
	at org.gbif.ipt.task.GenerateDataPackage.call(GenerateDataPackage.java:137)
	at org.gbif.ipt.task.GenerateDataPackage.call(GenerateDataPackage.java:77)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.frictionlessdata.tableschema.exception.TypeInferringException
	at io.frictionlessdata.tableschema.field.NumberField.parseValue(NumberField.java:87)
	at io.frictionlessdata.tableschema.field.NumberField.parseValue(NumberField.java:22)
	at io.frictionlessdata.tableschema.field.Field.castValue(Field.java:266)
	... 17 more
```

**Comment by mike-podolskiy90** [comment]
There are two reasons:

1.  Number format issue. datapackage libraries can't process numbers with a comma decimal delimiter
2. Wrong field type for the field `assertionUnit` in the data package schema (see https://github.com/gbif/rs.gbif.org/commit/e64f6bb0924b3c9a683c333210ddce63ba157129)
