### ISSUE TITLE
Agouti CamtrapDP on IPT3 error: Problem occurred while adding metadata file to data package folder 

### ISSUE THREAD

**Issue by mnhn-paul** [gbif/ipt#2287]
I created a new CamptrapDP dataset on our IPT3 instance (updated today #2285).

this is the archive I downloaded from Agouti : 

[personal-camera-trap-data-paul-braun-20240122153410.zip](https://github.com/gbif/ipt/files/14012590/personal-camera-trap-data-paul-braun-20240122153410.zip)

After importing the camtrapPD from Agouti some fields in the metadata are not filled in, I simply filled them in, saved and tried to publish the dataset on the IPT.

![image](https://github.com/gbif/ipt/assets/26623703/d59dcf99-3b25-4940-a172-d1c4b1adb314)
![image](https://github.com/gbif/ipt/assets/26623703/74c2bd97-74e3-412f-a515-4a284fc58939)

When trying to publish he dataset via the IPT I get an error:

![image](https://github.com/gbif/ipt/assets/26623703/808155dc-430e-4bb8-bc5e-917e02fdfba6)

The IPT logs give me this message:

```
ERROR 22-Jan-2024 16:03:15 [org.gbif.utils.file.CompressionUtil] - More than one root directory at /var/lib/ipt/tmp/dir5457817794907539728
ERROR 22-Jan-2024 16:03:19 [org.gbif.ipt.action.manage.DataPackageMetadataAction] - Wrong type of the stored inferred metadata class, expected InferredCamtrapMetadata got InferredEmlMetadata
ERROR 22-Jan-2024 16:03:31 [org.gbif.ipt.action.manage.DataPackageMetadataAction] - Wrong type of the stored inferred metadata class, expected InferredCamtrapMetadata got InferredEmlMetadata
ERROR 22-Jan-2024 16:03:58 [org.gbif.ipt.action.manage.DataPackageMetadataAction] - Wrong type of the stored inferred metadata class, expected InferredCamtrapMetadata got InferredEmlMetadata
ERROR 22-Jan-2024 16:04:10 [org.gbif.ipt.action.manage.DataPackageMetadataAction] - Wrong type of the stored inferred metadata class, expected InferredCamtrapMetadata got InferredEmlMetadata
ERROR 22-Jan-2024 16:04:10 [org.gbif.ipt.action.manage.DataPackageMetadataAction] - Wrong type of the stored inferred metadata class, expected InferredCamtrapMetadata got InferredEmlMetadata
ERROR 22-Jan-2024 16:04:21 [org.gbif.ipt.task.GenerateDataPackage] - Exception occurred trying to generate data package for resource test data camtrapPD (testtt): Problem occurred while adding metadata file to data package folder
org.gbif.ipt.task.GeneratorException: Problem occurred while adding metadata file to data package folder
	at org.gbif.ipt.task.GenerateDataPackage.addMetadata(GenerateDataPackage.java:800) ~[classes/:?]
	at org.gbif.ipt.task.GenerateDataPackage.call(GenerateDataPackage.java:130) [classes/:?]
	at org.gbif.ipt.task.GenerateDataPackage.call(GenerateDataPackage.java:77) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: io.frictionlessdata.datapackage.exceptions.DataPackageException: Unrecognized field "lastName" (class io.frictionlessdata.datapackage.Contributor), not marked as ignorable (5 known properties: "title", "organization", "email", "path", "role"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.frictionlessdata.datapackage.Contributor["lastName"])
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:71) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:85) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:95) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Package.setJson(Package.java:775) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Package.<init>(Package.java:219) ~[datapackage-java-0.6.14-gbif.jar:?]
	at org.gbif.ipt.task.GenerateDataPackage.addCamtrapMetadata(GenerateDataPackage.java:828) ~[classes/:?]
	at org.gbif.ipt.task.GenerateDataPackage.addMetadata(GenerateDataPackage.java:792) ~[classes/:?]
	... 6 more
Caused by: java.lang.IllegalArgumentException: Unrecognized field "lastName" (class io.frictionlessdata.datapackage.Contributor), not marked as ignorable (5 known properties: "title", "organization", "email", "path", "role"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.frictionlessdata.datapackage.Contributor["lastName"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4449) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4380) ~[jackson-databind-2.14.0.jar:2.14.0]
	at io.frictionlessdata.tableschema.util.JsonUtil.convertValue(JsonUtil.java:143) ~[tableschema-java-0.6.14.1-gbif.jar:?]
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:59) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:85) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:95) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Package.setJson(Package.java:775) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Package.<init>(Package.java:219) ~[datapackage-java-0.6.14-gbif.jar:?]
	at org.gbif.ipt.task.GenerateDataPackage.addCamtrapMetadata(GenerateDataPackage.java:828) ~[classes/:?]
	at org.gbif.ipt.task.GenerateDataPackage.addMetadata(GenerateDataPackage.java:792) ~[classes/:?]
	... 6 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "lastName" (class io.frictionlessdata.datapackage.Contributor), not marked as ignorable (5 known properties: "title", "organization", "email", "path", "role"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.frictionlessdata.datapackage.Contributor["lastName"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1132) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2202) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1705) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1683) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4444) ~[jackson-databind-2.14.0.jar:2.14.0]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4380) ~[jackson-databind-2.14.0.jar:2.14.0]
	at io.frictionlessdata.tableschema.util.JsonUtil.convertValue(JsonUtil.java:143) ~[tableschema-java-0.6.14.1-gbif.jar:?]
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:59) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:85) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Contributor.fromJson(Contributor.java:95) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Package.setJson(Package.java:775) ~[datapackage-java-0.6.14-gbif.jar:?]
	at io.frictionlessdata.datapackage.Package.<init>(Package.java:219) ~[datapackage-java-0.6.14-gbif.jar:?]
	at org.gbif.ipt.task.GenerateDataPackage.addCamtrapMetadata(GenerateDataPackage.java:828) ~[classes/:?]
	at org.gbif.ipt.task.GenerateDataPackage.addMetadata(GenerateDataPackage.java:792) ~[classes/:?]
	... 6 more
ERROR 22-Jan-2024 16:04:21 [org.gbif.ipt.service.manage.impl.ResourceManagerImpl] - Failed to roll back version #1.0. Could not find version to restore
```

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue, I'll have a look

**Comment by mike-podolskiy90** [comment]
Publication error is due to addition of new fields to the Contributor object: `firstName` and `lastName`. Should be fixed now.

Most of empty fields are absent in the source package, so it's fine. The only issue is contributors - I created a task for that https://github.com/gbif/ipt/issues/2289

**Comment by mike-podolskiy90** [comment]
Please update to the latest snapshot version, it should be fine

**Comment by mnhn-paul** [comment]
@raffael-mnhn

**Comment by mnhn-paul** [comment]
thanks @mike-podolskiy90 publication now works.
If I see correctly registration of camtrapDP  to gbif-uat.org  is currently disabled.

is that to be expected?

thanks 

![image](https://github.com/gbif/ipt/assets/26623703/c13aff22-8d21-40be-aa54-5e14bdce4e11)

**Comment by vechocho** [comment]
same problem on ipt3.gbif-uat.org

![image](https://github.com/gbif/ipt/assets/13081080/eb951898-4200-47b3-95cc-f25e642b6202)

**Comment by mike-podolskiy90** [comment]
No, it's not. I'll allow it for camtrap resources

**Comment by mike-podolskiy90** [comment]
@vechocho I've just checked logs - it's because of `homepage` field. Frictionless expects it to be with the protocol. I've updated the field and publication went fine. I'll create an issue for that

**Comment by vechocho** [comment]
Thank you a lot.

**Comment by mnhn-paul** [comment]
> No, it's not. I'll allow it for camtrap resources

thanks, looking forward to it
