### ISSUE TITLE
Align URL validation for the IPT and Frictionless

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2313]
IPT reports:
```
Publishing version #2.0 of resource more_camtrap failed: Archive generation for resource more_camtrap failed: Problem occurred while adding metadata file to data package folder
```

Stacktrace from logs:
```
org.gbif.ipt.task.GeneratorException: Problem occurred while adding metadata file to data package folder
	at org.gbif.ipt.task.GenerateDataPackage.addMetadata(GenerateDataPackage.java:800) ~[classes/:?]
	at org.gbif.ipt.task.GenerateDataPackage.call(GenerateDataPackage.java:130) [classes/:?]
	at org.gbif.ipt.task.GenerateDataPackage.call(GenerateDataPackage.java:77) [classes/:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: io.frictionlessdata.datapackage.exceptions.DataPackageException: Homepage URL must be fully qualified
	at io.frictionlessdata.datapackage.Package.setHomepage(Package.java:850) ~[datapackage-java-0.6.16.1-gbif-SNAPSHOT.jar:?]
	at io.frictionlessdata.datapackage.Package.setJson(Package.java:788) ~[datapackage-java-0.6.16.1-gbif-SNAPSHOT.jar:?]
	at io.frictionlessdata.datapackage.Package.<init>(Package.java:220) ~[datapackage-java-0.6.16.1-gbif-SNAPSHOT.jar:?]
	at org.gbif.ipt.task.GenerateDataPackage.addCamtrapMetadata(GenerateDataPackage.java:828) ~[classes/:?]
	at org.gbif.ipt.task.GenerateDataPackage.addMetadata(GenerateDataPackage.java:792) ~[classes/:?]
	... 6 more
```

**Comment by mike-podolskiy90** [comment]
Frictionless libraries validate URLs more thoroughly than IPT, it needs to be align.

Example
URL https://www.gg.wp is considered valid by IPT, but invalid by the frictionless library (`.wp` is invalid domain)

**Comment by mike-podolskiy90** [comment]
related issue #2290
