### ISSUE TITLE
Unforeseen error while editing geographic coverage metadata

### ISSUE THREAD

**Issue by kephelps** [gbif/ipt#2414]
It seems I have "discovered an unforeseen error" when modifying metadata. This is the resulting technical details provided: 
java.lang.NullPointerException
	at org.gbif.ipt.action.manage.MetadataAction.prepare(MetadataAction.java:313)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.gbif.ipt.struts2.DefaultLocaleInterceptor.intercept(DefaultLocaleInterceptor.java:42)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:134)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:106)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:54)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48)
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574)
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mike-podolskiy90** [comment]
Thank you for reporting the issue @kephelps 
What IPT version do you use please?

**Comment by mike-podolskiy90** [comment]
Thank you. Please describe when exactly error occurred?

**Comment by mike-podolskiy90** [comment]
I assume this is the [resource](https://ipt.vertnet.org/manage/metadata-geocoverage.do?r=lacm_ento) ?
I'm trying to reproduce the error to understand the reason.

**Comment by kephelps** [comment]
Unfortunately, when I click the resource link I receive this message "We are sorry, but you don't have the appropriate role to manage the requested resource. Please ask your administrator or the resource creator to give you an appropriate manager role." David Bloom is likely the administrator and may have access.

**Comment by mike-podolskiy90** [comment]
I don't think I understand. Now you don't have rights to edit that resource? What was your resource please? I have access to the VertNet IPT

**Comment by dbloom** [comment]
@mike-podolskiy90 I'll meet with @kephelps later this week to suss things out. The link to the resource you have provided above is to a different resource at LACM. She does not have access to those. This is the correct [resource](https://ipt.vertnet.org/manage/resource?r=eha_wabnet). It is set up as meta-data only, which is a residual of what we anticipated would be the best way to publish initially. This has changed and I suspect this needs to be changed to an occurrence dataset.

I am not, however, able to interpret the error kephelps posted in the original comment. I do not know any more about where the error occurred although have requested some additional information.

**Comment by mike-podolskiy90** [comment]
Thanks David, I'll investigate and see what the problem might be.

**Comment by dbloom** [comment]
@mike-podolskiy90 I've just had a brief email exchange with @kephelps and during her adventures updating metadata said the following: "I was just attempting to crop the bounding coordinates to Western Asia in the broad sense versus global. I changed the North coordinate from default 90 to 70 and the map trimmed some off the top of the global map, then I changed it to 60 but this time I hit enter (out of habit), and to me, that seemed to trigger the error message."

Just a moment ago I logged into the IPT to see if I can replicate, but when I open the metadata I am presented with:

![Screen Shot 2024-05-07 at 1 48 25 PM](https://github.com/gbif/ipt/assets/942447/08ab7863-778c-4ea3-a101-5d03a9730916)

So I can't actually modify anything. The logs are still accessible.

If needed, because this is a new resource and we haven't actually done much with it yet, I could delete this one and create a new one, but I will wait to hear from you before I do anything of the sort. Thanks for having a look.

**Comment by mike-podolskiy90** [comment]
Thank you, I think I see the problem now. You can re-create the resource if needed.

**Comment by dbloom** [comment]
Is there a fix on my end or would deletion and re-creation be the best option?

**Comment by mike-podolskiy90** [comment]
No, I'm afraid there's no fix on your end. I'll try to release a patched version this week to prevent this from happening.

**Comment by dbloom** [comment]
Excellent. Thanks MIke. I'll take care of this resource and meet with kephelps later this week to get the process moving again.

**Comment by kephelps** [comment]
Thank you both for your help in resolving this issue.

**Comment by mike-podolskiy90** [comment]
Deployed to https://ipt.vertnet.org/
