### ISSUE TITLE
IPT HTTP 500: java.lang.NoClassDefFoundError: javax/el/ELManager   at org.gbif.ipt.action.manage.OverviewAction

### ISSUE THREAD

**Issue by PietrH** [gbif/ipt#2436]
I updated our production IPT to 3.0.4, we have since successfully updated datasets on GBIF. I'm not sure if we have published new ones. 

When opening a resource when logged in: `/manage/resource/` for any resource, I am getting the following HTTP 500 internal server error; 

```
HTTP Status 500 - Unable to instantiate Action, org.gbif.ipt.action.manage.OverviewAction, defined for 'resource' in namespace '/manage'Unable to provision, see the following errors:

type Exception report

message Unable to instantiate Action, org.gbif.ipt.action.manage.OverviewAction, defined for 'resource' in namespace '/manage'Unable to provision, see the following errors:

description The server encountered an internal error that prevented it from fulfilling this request.

exception

Unable to instantiate Action, org.gbif.ipt.action.manage.OverviewAction,  defined for 'resource' in namespace '/manage'Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: javax/el/ELManager
  at org.gbif.ipt.action.manage.OverviewAction.<init>(OverviewAction.java:183)
  while locating org.gbif.ipt.action.manage.OverviewAction

1 error - action - file:/var/lib/tomcat/webapps/ROOT/WEB-INF/classes/struts-manage.xml:96:79
	com.opensymphony.xwork2.DefaultActionInvocation.createAction(DefaultActionInvocation.java:320)
	com.opensymphony.xwork2.DefaultActionInvocation.init(DefaultActionInvocation.java:401)
	com.opensymphony.xwork2.DefaultActionProxy.prepare(DefaultActionProxy.java:201)
	org.apache.struts2.factory.StrutsActionProxy.prepare(StrutsActionProxy.java:57)
	org.apache.struts2.factory.StrutsActionProxyFactory.createActionProxy(StrutsActionProxyFactory.java:32)
	com.opensymphony.xwork2.DefaultActionProxyFactory.createActionProxy(DefaultActionProxyFactory.java:60)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:564)
	org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
	org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)

root cause

com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: javax/el/ELManager
  at org.gbif.ipt.action.manage.OverviewAction.<init>(OverviewAction.java:183)
  while locating org.gbif.ipt.action.manage.OverviewAction

1 error
	com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
	com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	com.google.inject.struts2.Struts2Factory.buildBean(Struts2Factory.java:110)
	com.opensymphony.xwork2.ObjectFactory.buildBean(ObjectFactory.java:191)
	com.opensymphony.xwork2.ObjectFactory.buildBean(ObjectFactory.java:177)
	com.opensymphony.xwork2.factory.DefaultActionFactory.buildAction(DefaultActionFactory.java:40)
	com.opensymphony.xwork2.ObjectFactory.buildAction(ObjectFactory.java:142)
	com.opensymphony.xwork2.DefaultActionInvocation.createAction(DefaultActionInvocation.java:301)
	com.opensymphony.xwork2.DefaultActionInvocation.init(DefaultActionInvocation.java:401)
	com.opensymphony.xwork2.DefaultActionProxy.prepare(DefaultActionProxy.java:201)
	org.apache.struts2.factory.StrutsActionProxy.prepare(StrutsActionProxy.java:57)
	org.apache.struts2.factory.StrutsActionProxyFactory.createActionProxy(StrutsActionProxyFactory.java:32)
	com.opensymphony.xwork2.DefaultActionProxyFactory.createActionProxy(DefaultActionProxyFactory.java:60)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:564)
	org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
	org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)

root cause

java.lang.NoClassDefFoundError: javax/el/ELManager
	org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:171)
	org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.<init>(ResourceBundleMessageInterpolator.java:94)
	org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getDefaultMessageInterpolator(AbstractConfigurationImpl.java:573)
	org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getDefaultMessageInterpolatorConfiguredWithClassLoader(AbstractConfigurationImpl.java:822)
	org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getMessageInterpolator(AbstractConfigurationImpl.java:483)
	org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:154)
	org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
	org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:433)
	org.gbif.ipt.validation.DataPackageMetadataValidator.<init>(DataPackageMetadataValidator.java:56)
	org.gbif.ipt.action.manage.OverviewAction.<init>(OverviewAction.java:187)
	org.gbif.ipt.action.manage.OverviewAction$$FastClassByGuice$$36870dad.newInstance(<generated>)
	com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
	com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	com.google.inject.struts2.Struts2Factory.buildBean(Struts2Factory.java:110)
	com.opensymphony.xwork2.ObjectFactory.buildBean(ObjectFactory.java:191)
	com.opensymphony.xwork2.ObjectFactory.buildBean(ObjectFactory.java:177)
	com.opensymphony.xwork2.factory.DefaultActionFactory.buildAction(DefaultActionFactory.java:40)
	com.opensymphony.xwork2.ObjectFactory.buildAction(ObjectFactory.java:142)
	com.opensymphony.xwork2.DefaultActionInvocation.createAction(DefaultActionInvocation.java:301)
	com.opensymphony.xwork2.DefaultActionInvocation.init(DefaultActionInvocation.java:401)
	com.opensymphony.xwork2.DefaultActionProxy.prepare(DefaultActionProxy.java:201)
	org.apache.struts2.factory.StrutsActionProxy.prepare(StrutsActionProxy.java:57)
	org.apache.struts2.factory.StrutsActionProxyFactory.createActionProxy(StrutsActionProxyFactory.java:32)
	com.opensymphony.xwork2.DefaultActionProxyFactory.createActionProxy(DefaultActionProxyFactory.java:60)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:564)
	org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
	org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37)
	com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)


```

url: https://ipt.inbo.be/
OS version 	Linux 5.10.82-83.359.amzn2.x86_64
Java version 	11.0.13
Application server version 	Apache Tomcat/7.0.76
IPT mode 	PRODUCTION 

I'm aware we are running an unsupported version of tomcat, an update is in the works but might still be a while off. 

---

- `javax.el` is not included in the classpath, I believe this API is not included in tomcat 7, have I got that right? 
- Should I either downgrade my IPT version back to 2.7, or my tomcat version up to at least 8? Or is there any other way around this?

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
IPT 3 does not work on Tomcat 7. It must be at least 8.

**Comment by mike-podolskiy90** [comment]
https://ipt.gbif.org/manual/en/ipt/latest/installation#tomcat

**Comment by PietrH** [comment]
Alright, I'll get started on updating tomcat then!

**Comment by PietrH** [comment]
After reinstalling tomcat to version 9.0.89 this is resolved. Thanks for the help!
