### ISSUE TITLE
Unforeseen error

### ISSUE THREAD

**Issue by guti181** [gbif/ipt#2545]
On the main screen, when clicking on "Login" button (top right), I'm getting the error below.
Pls advise.
Thx !

It seems you have discovered an unforeseen error:

Index: 0, Size: 0        
If you think this shouldn't have happened, would you mind helping us to improve the IPT and [file a small bug report](https://github.com/gbif/ipt/issues/new) for this exception?

Thanks a million, the IPT development team.

Technical Details
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.gbif.ipt.action.LoginAction.prepare(LoginAction.java:66)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.gbif.ipt.struts2.DefaultLocaleInterceptor.intercept(DefaultLocaleInterceptor.java:42)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:134)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.gbif.ipt.struts2.PrivateDeletedResourceInterceptor.intercept(PrivateDeletedResourceInterceptor.java:104)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:54)
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48)
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574)
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:761)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:383)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.lang.Thread.run(Unknown Source)

![Image](https://github.com/user-attachments/assets/9955fb06-4dfa-48c3-b76b-0482e9149cc7)

**Comment by mike-podolskiy90** [comment]
Thank you very much for reporting the issue. I'll get back to you

**Comment by mike-podolskiy90** [comment]
Does the problem persist? Can you log in after refreshing the page?

**Comment by guti181** [comment]
yes persist

**Comment by guti181** [comment]
doesn't it happen to you too ??
i'm using version 3.0.6
![Image](https://github.com/user-attachments/assets/be8296b1-916e-4e56-ae50-99ffbee126b9)

**Comment by mike-podolskiy90** [comment]
No, I've logged in successfully. What is your IPT please?

**Comment by guti181** [comment]
you mean what web server ?
i'm using tomcat

**Comment by mike-podolskiy90** [comment]
I meant the public URL of the IPT.

**Comment by guti181** [comment]
Oh, sorry..
it's:
https://biogis.huji.ac.il/ipt
Does this help?
I'm afraid you won't be able to see the error i've sent above, since our WAF is blocking the access from outside when there are errors ..

**Comment by mike-podolskiy90** [comment]
Thank you. IPT health page states that there's no public access to the IPT and public URL should be absolute and resovable. I suppose those are the issues.

**Comment by guti181** [comment]
not sure i'm following ... what do you mean by "there's no public access to the IPT" ?
the URL is public and accessable.. why when i click on Login button i'm getting an error ?
besides, a few weeks ago we were able to access the login page, and now we're getting this error

**Comment by mike-podolskiy90** [comment]
Public URL setting is wrong (Health page):
![Image](https://github.com/user-attachments/assets/f67f0b59-e60a-4772-b0a9-238630aaa10e)

I assume public URL should be:
https://biogis.huji.ac.il/ipt    (instead of relative path that is currently set: /ipt)

Since you can't log in that setting can be changed internally on the server in the config files (/config/ipt.properties -> ipt.baseURL)

**Comment by guti181** [comment]
Have fixed and health status is OK now, but the login issue is still on :/ Same error

![Image](https://github.com/user-attachments/assets/70538c38-97ea-4939-ac75-3131968e2479)

**Comment by mike-podolskiy90** [comment]
I see. I suspect there's no any admins in the users.xml file (config directory; IPT requires at least one). It might be the user was deleted somehow. Make sure there's one present there

Example of the users.xml file:
```xml
<users>
  <user email="mpodolskiy@gbif.org" password="***" firstname="Mikhail" lastname="Podolskiy" role="Admin" lastLogin="2024-10-11 08:14:56.321 UTC"/>
</users>
```

See what password to set [here](https://ipt.gbif.org/manual/en/ipt/latest/faq#how-do-i-reset-the-admin-password)

**Comment by guti181** [comment]
I do have a user configured (have deleted the password here..)
As you can see, i was able to login about a month ago
<users>
  <user email="yaelgut@savion.huji.ac.il" password="****" firstname="Yael" lastname="Gutreich" role="Admin" lastLogin="2024-09-11 12:56:17.106 UTC"/>
</users>

**Comment by mike-podolskiy90** [comment]
It should work then. Could you restart your Tomcat please and tell me the result?

**Comment by guti181** [comment]
Ok, finally resolved ..... !
The issue was that i've restarted the tomcat by double clicking the shutdown.bat/startup.bat
I've tried now to restart it via cmd with admin previliges, and it's finaly working now :)
Thx ALOT for the prompt help !!

![Image](https://github.com/user-attachments/assets/5fcd11af-771b-4d80-b824-c2a70a567ee6)

**Comment by mike-podolskiy90** [comment]
I'm glad the issue has been resolved!
